export const programsData = {
   // Year 1 Only Cost Data
   year1Costs: [
      {
         program: "Diploma",
         perCredit: 100,
         year: "1 Year / 28 Credits",
         tuition: 2800,
         applicationFee: 50,
         adminFee: 250,
         libraryFee: 80,
         techFee: 100,
         totalFees: 3280,
         miscExp: 1600,
         costOfLiving: 8000,
         booksInsurance: 2500,
         total: 15380,
      },
      {
         program: "Bachelors",
         perCredit: 150,
         year: "1 Year / 40 Credits",
         tuition: 6000,
         applicationFee: 50,
         adminFee: 500,
         libraryFee: 300,
         techFee: 200,
         totalFees: 7050,
         miscExp: 1600,
         costOfLiving: 8000,
         booksInsurance: 2500,
         total: 19150,
      },
      {
         program: "Masters",
         perCredit: 200,
         year: "1 Year / 30 Credits",
         tuition: 6000,
         applicationFee: 100,
         adminFee: 700,
         libraryFee: 400,
         techFee: 250,
         totalFees: 7450,
         miscExp: 1800,
         costOfLiving: 9000,
         booksInsurance: 3000,
         total: 22250,
      },
      {
         program: "Doctorate",
         perCredit: 250,
         year: "1 Year / 24 Credits",
         tuition: 6000,
         applicationFee: 150,
         adminFee: 1000,
         libraryFee: 500,
         techFee: 300,
         totalFees: 7950,
         miscExp: 2000,
         costOfLiving: 10000,
         booksInsurance: 3500,
         total: 23450,
      },
   ],

   // Full Program Cost Data
   fullProgramCosts: [
      {
         program: "Diploma",
         perCredit: 100,
         year: "2 Years / 56 Credits",
         tuition: 5600,
         applicationFee: 50,
         adminFee: 500,
         libraryFee: 160,
         techFee: 200,
         totalFees: 6510,
         miscExp: 3200,
         costOfLiving: 16000,
         booksInsurance: 5000,
         total: 27510,
      },
      {
         program: "Bachelors",
         perCredit: 150,
         year: "4 Years / 160 Credits",
         tuition: 24000,
         applicationFee: 50,
         adminFee: 2000,
         libraryFee: 1200,
         techFee: 800,
         totalFees: 28050,
         miscExp: 6400,
         costOfLiving: 32000,
         booksInsurance: 10000,
         total: 76450,
      },
      {
         program: "Masters",
         perCredit: 200,
         year: "2 Years / 60 Credits",
         tuition: 12000,
         applicationFee: 100,
         adminFee: 1400,
         libraryFee: 800,
         techFee: 500,
         totalFees: 14700,
         miscExp: 3600,
         costOfLiving: 18000,
         booksInsurance: 6000,
         total: 42300,
      },
      {
         program: "Doctorate",
         perCredit: 250,
         year: "3 Years / 72 Credits",
         tuition: 18000,
         applicationFee: 150,
         adminFee: 3000,
         libraryFee: 1500,
         techFee: 900,
         totalFees: 23550,
         miscExp: 6000,
         costOfLiving: 30000,
         booksInsurance: 7500,
         total: 67050,
      },
   ],
};

export const countries = [
   "Afghanistan",
   "Albania",
   "Algeria",
   "Andorra",
   "Angola",
   "Antigua and Barbuda",
   "Argentina",
   "Armenia",
   "Australia",
   "Austria",
   "Azerbaijan",
   "Bahamas",
   "Bahrain",
   "Bangladesh",
   "Barbados",
   "Belarus",
   "Belgium",
   "Belize",
   "Benin",
   "Bhutan",
   "Bolivia",
   "Bosnia and Herzegovina",
   "Botswana",
   "Brazil",
   "Brunei",
   "Bulgaria",
   "Burkina Faso",
   "Burundi",
   "Cabo Verde",
   "Cambodia",
   "Cameroon",
   "Canada",
   "Central African Republic",
   "Chad",
   "Chile",
   "China",
   "Colombia",
   "Comoros",
   "Congo (Congo-Brazzaville)",
   "Costa Rica",
   "Croatia",
   "Cuba",
   "Cyprus",
   "Czech Republic (Czechia)",
   "Denmark",
   "Djibouti",
   "Dominica",
   "Dominican Republic",
   "Ecuador",
   "Egypt",
   "El Salvador",
   "Equatorial Guinea",
   "Eritrea",
   "Estonia",
   "Eswatini (fmr. 'Swaziland')",
   "Ethiopia",
   "Fiji",
   "Finland",
   "France",
   "Gabon",
   "Gambia",
   "Georgia",
   "Germany",
   "Ghana",
   "Greece",
   "Grenada",
   "Guatemala",
   "Guinea",
   "Guinea-Bissau",
   "Guyana",
   "Haiti",
   "Honduras",
   "Hungary",
   "Iceland",
   "India",
   "Indonesia",
   "Iran",
   "Iraq",
   "Ireland",
   "Israel",
   "Italy",
   "Jamaica",
   "Japan",
   "Jordan",
   "Kazakhstan",
   "Kenya",
   "Kiribati",
   "Kuwait",
   "Kyrgyzstan",
   "Laos",
   "Latvia",
   "Lebanon",
   "Lesotho",
   "Liberia",
   "Libya",
   "Liechtenstein",
   "Lithuania",
   "Luxembourg",
   "Madagascar",
   "Malawi",
   "Malaysia",
   "Maldives",
   "Mali",
   "Malta",
   "Marshall Islands",
   "Mauritania",
   "Mauritius",
   "Mexico",
   "Micronesia",
   "Moldova",
   "Monaco",
   "Mongolia",
   "Montenegro",
   "Morocco",
   "Mozambique",
   "Myanmar (formerly Burma)",
   "Namibia",
   "Nauru",
   "Nepal",
   "Netherlands",
   "New Zealand",
   "Nicaragua",
   "Niger",
   "Nigeria",
   "North Korea",
   "North Macedonia",
   "Norway",
   "Oman",
   "Pakistan",
   "Palau",
   "Palestine State",
   "Panama",
   "Papua New Guinea",
   "Paraguay",
   "Peru",
   "Philippines",
   "Poland",
   "Portugal",
   "Qatar",
   "Romania",
   "Russia",
   "Rwanda",
   "Saint Kitts and Nevis",
   "Saint Lucia",
   "Saint Vincent and the Grenadines",
   "Samoa",
   "San Marino",
   "Sao Tome and Principe",
   "Saudi Arabia",
   "Senegal",
   "Serbia",
   "Seychelles",
   "Sierra Leone",
   "Singapore",
   "Slovakia",
   "Slovenia",
   "Solomon Islands",
   "Somalia",
   "South Africa",
   "South Korea",
   "South Sudan",
   "Spain",
   "Sri Lanka",
   "Sudan",
   "Suriname",
   "Sweden",
   "Switzerland",
   "Syria",
   "Taiwan",
   "Tajikistan",
   "Tanzania",
   "Thailand",
   "Timor-Leste",
   "Togo",
   "Tonga",
   "Trinidad and Tobago",
   "Tunisia",
   "Turkey",
   "Turkmenistan",
   "Tuvalu",
   "Uganda",
   "Ukraine",
   "United Arab Emirates",
   "United Kingdom",
   "United States of America",
   "Uruguay",
   "Uzbekistan",
   "Vanuatu",
   "Vatican City",
   "Venezuela",
   "Vietnam",
   "Yemen",
   "Zambia",
   "Zimbabwe",
];
